# vim: nospell
#
language: c
dist: trusty
sudo: false

cache:
  timeout: 600
  directories:
    - $HOME/.stack/snapshots
    - .stack-work/install

before_cache:
  - rm -vrf $(stack path --local-install-root)/bin
  - rm -rf  $(stack path --local-install-root)/doc

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-2.0

compiler:
  - GHC-8.4.1
  - GHC-8.2.2
  - GHC-8.0.2
  - GHC-7.10.3

env:
  global:
    - CABAL=2.0

matrix:
  fast_finish: true
  # allow_failures:

before_install:
  - export PATH=/opt/cabal/$CABAL/bin:$HOME/.cabal/bin:$PATH
  - export GHC=${CC:4}
  - unset CC
  - source .travis/install-stack.sh

install:
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal --version
  - stack --version
  - travis_retry stack build --no-terminal --dry-run
  - travis_retry stack build --no-terminal --fast --only-dependencies --no-haddock-deps

script:
  - travis_retry stack build --no-terminal --fast --haddock --no-haddock-deps
  - travis_retry stack test

after_success:
  - source .travis/update-accelerate-buildbot.sh

